CUDA_VISIBLE_DEVICES=1 python main.py \
--image_dir data/iu_xray/images/ \
--ann_path data/iu_xray/annotation.json \
--dataset_name iu_xray \
--max_seq_length 60 \
--threshold 3 \
--batch_size 16 \
--epochs 100 \
--save_dir /results/IU-X-Ray \
--d_vf 2048 \
--step_size 50 \
--gamma 0.1 \
--early_stop 100 \
--num_layers 3 \
--rm_num_slots 5 \
--seed 11291